// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as kube$0 from "../../../../roger/k8sdockside/internal/kube/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "node:drain": kube$0.DrainProgress;
            "pod:logs": kube$0.LogBatch;
            "resource:snapshot": kube$0.Snapshot;
        }
    }
}
