// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionService performs the operations that change a cluster from a button:
 * deleting an object, scaling or restarting a workload, cordoning or draining a
 * node.
 * 
 * It is a separate service from ResourceService because the two answer
 * different questions -- one serves what a cluster contains, this one changes
 * it -- but they share a watcher, and so a client pool. A context already open
 * in a tab costs no second connection and no second credential exec when you
 * act on something in it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kube$0 from "./internal/kube/models.js";

/**
 * CancelDrain calls off a drain in flight. The node stays cordoned: it is half
 * emptied, and quietly letting work back onto it is not what stopping meant.
 */
export function CancelDrain(drainID: string): $CancellablePromise<void> {
    return $Call.ByID(3170274829, drainID);
}

/**
 * Cordon closes a node to new work, or reopens it.
 */
export function Cordon(contextID: string, name: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(880635050, contextID, name, on);
}

/**
 * Delete removes one object from its cluster.
 */
export function Delete(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3592135412, contextID, kind, $namespace, name);
}

/**
 * Drain starts moving everything off a node and returns the ID its progress
 * will arrive under.
 * 
 * It returns as soon as the drain is under way. A drain takes minutes -- it
 * waits on disruption budgets, which is the point of using the eviction API --
 * so it reports through events rather than making the window wait.
 */
export function Drain(contextID: string, node: string): $CancellablePromise<string> {
    return $Call.ByID(4015294767, contextID, node);
}

/**
 * ObjectState reads the few facts the action bar needs about one object: what
 * its buttons should say, and what they should start from.
 */
export function ObjectState(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<kube$0.ObjectState> {
    return $Call.ByID(2884119641, contextID, kind, $namespace, name);
}

/**
 * Restart rolls a workload, the way `kubectl rollout restart` does.
 */
export function Restart(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2239457358, contextID, kind, $namespace, name);
}

/**
 * Scale sets a workload's replica count.
 */
export function Scale(contextID: string, kind: string, $namespace: string, name: string, replicas: number): $CancellablePromise<void> {
    return $Call.ByID(495812103, contextID, kind, $namespace, name, replicas);
}
