// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KubeconfigService is the frontend's view of the kubeconfig files on disk. It
 * caches the last scan so that opening tabs and rendering the sidebar does not
 * re-read every file, and rescans only when the user asks (Sync) or changes the
 * set of files.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kube$0 from "./internal/kube/models.js";

/**
 * AddFile remembers a kubeconfig path chosen by the user and rescans. The file
 * is parsed before being stored so that picking something that is not a
 * kubeconfig fails immediately, with a message, instead of quietly adding a
 * broken entry to the sidebar.
 */
export function AddFile(path: string): $CancellablePromise<kube$0.File[] | null> {
    return $Call.ByID(3638613851, path);
}

/**
 * BrowseForFile opens the native file picker and adds whatever the user chose.
 * It returns the new file list; cancelling the dialog leaves everything as it
 * was and is not an error.
 */
export function BrowseForFile(): $CancellablePromise<kube$0.File[] | null> {
    return $Call.ByID(2885395557);
}

/**
 * Contexts flattens the last scan into a single list, which is what the sidebar
 * actually renders.
 */
export function Contexts(): $CancellablePromise<kube$0.Context[] | null> {
    return $Call.ByID(2191471886);
}

/**
 * Files returns the last scan, running one first if the app has just started.
 */
export function Files(): $CancellablePromise<kube$0.File[] | null> {
    return $Call.ByID(3842656561);
}

/**
 * RemoveFile forgets a user-added kubeconfig. Auto-discovered files cannot be
 * removed -- the next sync would find them again -- so that is reported as an
 * error rather than appearing to work.
 */
export function RemoveFile(path: string): $CancellablePromise<kube$0.File[] | null> {
    return $Call.ByID(298433948, path);
}

/**
 * Sync rescans every source -- ~/.kube/config, $KUBECONFIG, the user's own
 * paths, and the rest of ~/.kube -- and returns what it found.
 */
export function Sync(): $CancellablePromise<kube$0.File[] | null> {
    return $Call.ByID(425383933);
}
