// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metrics$0 from "./internal/metrics/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "./internal/plugins/models.js";

/**
 * About is what the settings view's About section shows.
 */
export interface About {
    "version": string;
    "wails": string;
    "go": string;
    "platform": string;
}

/**
 * Panel is a surface's worth of charts, plus why there are none if there are
 * none.
 */
export interface Panel {
    /**
     * Attached is whether any installed plugin draws on this surface at all.
     * 
     * It is the difference between "there is nothing to show here" and "there is
     * something to show and it is empty", and only the second is worth drawing a
     * heading for. Without it every pod in a cluster with no charting plugin
     * would carry an empty Metrics section.
     */
    "attached": boolean;

    /**
     * Source is carried so the panel can say where the numbers came from, and
     * what to do when there are none.
     */
    "source": Source;
    "charts": plugins$0.ChartResult[] | null;
    "range": number;
}

/**
 * Source is where a context's metrics come from, for the settings view and for
 * the message a chart panel shows when there are none.
 */
export interface Source {
    "endpoint": metrics$0.Endpoint;

    /**
     * Configured is the override as the user typed it, so the settings field can
     * show it back.
     */
    "configured": string;

    /**
     * Available is whether there is anywhere to query at all.
     */
    "available": boolean;

    /**
     * Error is why we could not look, as opposed to having looked and found
     * nothing. A cluster that refused the request and a cluster with no
     * Prometheus need different things said about them.
     */
    "error": string;
}
