// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * About is what the settings view's About section shows.
 */
export interface About {
    "version": string;
    "wails": string;
    "go": string;
    "platform": string;
}
