// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService serves the cluster data behind each tab, live.
 * 
 * Tables are not fetched, they are subscribed to: Subscribe opens a watch and
 * returns immediately, and every change to the cluster arrives at the frontend
 * as a SnapshotEvent. The one-shot methods below (the dashboard, the describe
 * panel, the namespace filter) share the same connections.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kube$0 from "./internal/kube/models.js";

/**
 * ApplyYAML writes an edited object back to the cluster and returns it as the
 * server left it -- with the resourceVersion the next save will be checked
 * against, and whatever defaulting and admission control did to it on the way
 * in. The editor replaces its contents with the result, which is what makes a
 * second save work rather than fail as a conflict.
 */
export function ApplyYAML(contextID: string, kind: string, $namespace: string, name: string, yaml: string): $CancellablePromise<string> {
    return $Call.ByID(1166098740, contextID, kind, $namespace, name, yaml);
}

/**
 * CheckYAML reports whether what is in the editor is still YAML. It touches no
 * cluster: it is called as the user types, and the only question it answers is
 * whether the document parses.
 */
export function CheckYAML(yaml: string): $CancellablePromise<kube$0.YAMLCheck> {
    return $Call.ByID(3233044240, yaml);
}

/**
 * CustomResourceKinds lists what a cluster defines, grouped by API group, for
 * the definitions section of the sidebar.
 */
export function CustomResourceKinds(contextID: string): $CancellablePromise<kube$0.CustomResourceGroup[] | null> {
    return $Call.ByID(1195675545, contextID);
}

/**
 * Describe renders the detail report shown in the slide-in panel.
 */
export function Describe(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2123095632, contextID, kind, $namespace, name);
}

/**
 * HelmReleases lists the Helm releases installed in a cluster.
 * 
 * It is a plain call rather than a subscription because Helm releases are not a
 * watchable resource: they are Secrets whose payload has to be decoded, and
 * that payload is exactly what must not be kept in the informer cache. The
 * table is built and the payload dropped in the same breath.
 */
export function HelmReleases(contextID: string, $namespace: string): $CancellablePromise<kube$0.Table> {
    return $Call.ByID(4249468707, contextID, $namespace);
}

/**
 * Namespaces lists the namespaces available for the namespace filter.
 */
export function Namespaces(contextID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3241415649, contextID);
}

/**
 * Overview is the dashboard payload for one context.
 */
export function Overview(contextID: string): $CancellablePromise<kube$0.Overview> {
    return $Call.ByID(4169493298, contextID);
}

/**
 * Ping reports whether a context's cluster can be reached, for the sidebar's
 * connection indicator. It returns nil when the cluster answered and an error
 * carrying the reason when it did not; there is no payload because the only
 * question being asked is whether this works.
 */
export function Ping(contextID: string): $CancellablePromise<void> {
    return $Call.ByID(1821171873, contextID);
}

/**
 * ResourceYAML returns one object as the YAML the editor opens with. It is a
 * live read rather than the informer's copy: the cache drops managed fields and
 * redacts secret values, and an editor must open on the object rather than on
 * the table's view of it.
 */
export function ResourceYAML(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2893618278, contextID, kind, $namespace, name);
}

/**
 * SetNamespace re-points an open subscription at another namespace. The watch
 * is cluster-wide, so this is a filter change: the new rows arrive as an event
 * without anything being re-fetched.
 */
export function SetNamespace(subscriptionID: string, $namespace: string): $CancellablePromise<void> {
    return $Call.ByID(459766854, subscriptionID, $namespace);
}

/**
 * Subscribe opens a live view of one resource kind and returns the subscription
 * ID that its snapshots will carry. Pass an empty namespace for all namespaces.
 * 
 * It returns as soon as the watch is started. The first rows arrive as an event
 * once the cluster has answered, so a slow or unreachable cluster leaves the
 * tab in its loading state rather than blocking the UI.
 */
export function Subscribe(contextID: string, kind: string, $namespace: string): $CancellablePromise<string> {
    return $Call.ByID(760258811, contextID, kind, $namespace);
}

/**
 * Unsubscribe closes a tab's view. The underlying watch stays open if another
 * tab is still using it.
 */
export function Unsubscribe(subscriptionID: string): $CancellablePromise<void> {
    return $Call.ByID(4293577118, subscriptionID);
}
