// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService serves the cluster data behind each tab, live.
 * 
 * Tables are not fetched, they are subscribed to: Subscribe opens a watch and
 * returns immediately, and every change to the cluster arrives at the frontend
 * as a SnapshotEvent. The one-shot methods below (the dashboard, the describe
 * panel, the namespace filter) share the same connections.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kube$0 from "./internal/kube/models.js";

/**
 * Describe renders the detail report shown in the slide-in panel.
 */
export function Describe(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2123095632, contextID, kind, $namespace, name);
}

/**
 * Namespaces lists the namespaces available for the namespace filter.
 */
export function Namespaces(contextID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3241415649, contextID);
}

/**
 * Overview is the dashboard payload for one context.
 */
export function Overview(contextID: string): $CancellablePromise<kube$0.Overview> {
    return $Call.ByID(4169493298, contextID);
}

/**
 * Ping reports whether a context's cluster can be reached, for the sidebar's
 * connection indicator. It returns nil when the cluster answered and an error
 * carrying the reason when it did not; there is no payload because the only
 * question being asked is whether this works.
 */
export function Ping(contextID: string): $CancellablePromise<void> {
    return $Call.ByID(1821171873, contextID);
}

/**
 * SetNamespace re-points an open subscription at another namespace. The watch
 * is cluster-wide, so this is a filter change: the new rows arrive as an event
 * without anything being re-fetched.
 */
export function SetNamespace(subscriptionID: string, $namespace: string): $CancellablePromise<void> {
    return $Call.ByID(459766854, subscriptionID, $namespace);
}

/**
 * Subscribe opens a live view of one resource kind and returns the subscription
 * ID that its snapshots will carry. Pass an empty namespace for all namespaces.
 * 
 * It returns as soon as the watch is started. The first rows arrive as an event
 * once the cluster has answered, so a slow or unreachable cluster leaves the
 * tab in its loading state rather than blocking the UI.
 */
export function Subscribe(contextID: string, kind: string, $namespace: string): $CancellablePromise<string> {
    return $Call.ByID(760258811, contextID, kind, $namespace);
}

/**
 * Unsubscribe closes a tab's view. The underlying watch stays open if another
 * tab is still using it.
 */
export function Unsubscribe(subscriptionID: string): $CancellablePromise<void> {
    return $Call.ByID(4293577118, subscriptionID);
}
