// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService serves the cluster data behind each tab.
 * 
 * The data is currently fabricated (see internal/kube/stub.go) but is shaped
 * exactly like the real thing and is stable per context, so the UI can be built
 * against it. Wiring in client-go means changing what these methods call, not
 * their signatures or the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kube$0 from "./internal/kube/models.js";

/**
 * Describe renders the detail report shown in the slide-in panel.
 */
export function Describe(contextID: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2123095632, contextID, kind, $namespace, name);
}

/**
 * Namespaces lists the namespaces available for the namespace filter.
 */
export function Namespaces(contextID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3241415649, contextID);
}

/**
 * Overview is the dashboard payload for one context.
 */
export function Overview(contextID: string): $CancellablePromise<kube$0.Overview> {
    return $Call.ByID(4169493298, contextID);
}

/**
 * Table lists one resource kind, optionally restricted to a namespace. Pass an
 * empty namespace for all namespaces.
 */
export function Table(contextID: string, kind: string, $namespace: string): $CancellablePromise<kube$0.Table> {
    return $Call.ByID(2790760663, contextID, kind, $namespace);
}
