// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes the persisted user preferences to the frontend: the
 * per-context alias and colour, the tab order, the window layout, and the
 * app-wide preferences the settings view edits. Every mutator returns the full
 * settings so the frontend can replace its state with what actually reached
 * disk rather than assuming its optimistic update stuck.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconfig$0 from "./internal/appconfig/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * About reports what this build is. The values come from the binary's own
 * build info rather than a constant, so a development build says so instead of
 * claiming whatever number was last committed.
 */
export function About(): $CancellablePromise<$models.About> {
    return $Call.ByID(159705297);
}

/**
 * ConfigPath is where the settings file lives, shown in the UI so the user can
 * find it.
 */
export function ConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(4272892441);
}

/**
 * Get returns everything the user has customised.
 */
export function Get(): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(710695688);
}

/**
 * RevealConfig opens the settings file in the platform's file manager with the
 * file itself selected, which is the useful thing to offer next to a path the
 * user cannot click. The path comes from the store rather than the frontend so
 * that nothing the webview says can decide what gets opened.
 * 
 * Nothing may have been saved yet -- Open deliberately creates no file -- so a
 * missing one falls back to its directory rather than failing. That is still
 * the answer to "where does this live?", which is what was asked.
 */
export function RevealConfig(): $CancellablePromise<void> {
    return $Call.ByID(2343047891);
}

/**
 * SetContextPrefs saves the display name and colour for one context. Clearing
 * both fields resets the context to its defaults.
 */
export function SetContextPrefs(id: string, prefs: appconfig$0.ContextPrefs): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(3214323715, id, prefs);
}

/**
 * SetLayout saves the sidebar width and the detail panel's dock and size.
 */
export function SetLayout(layout: appconfig$0.Layout): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(1286510778, layout);
}

/**
 * SetPreferences saves the app-wide preferences: theme, density, font size,
 * whether tabs are restored at launch, and whether removing a kubeconfig
 * source asks first.
 */
export function SetPreferences(prefs: appconfig$0.Preferences): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(357209814, prefs);
}

/**
 * SetTabOrder saves the order the user dragged their tabs into.
 */
export function SetTabOrder(order: appconfig$0.TabRef[] | null): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(477788357, order);
}
