// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes the persisted user preferences to the frontend: the
 * per-context alias and colour, the tab order, and the window layout. Every
 * mutator returns the full settings so the frontend can replace its state with
 * what actually reached disk rather than assuming its optimistic update stuck.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconfig$0 from "./internal/appconfig/models.js";

/**
 * ConfigPath is where the settings file lives, shown in the UI so the user can
 * find it.
 */
export function ConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(4272892441);
}

/**
 * Get returns everything the user has customised.
 */
export function Get(): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(710695688);
}

/**
 * SetContextPrefs saves the display name and colour for one context. Clearing
 * both fields resets the context to its defaults.
 */
export function SetContextPrefs(id: string, prefs: appconfig$0.ContextPrefs): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(3214323715, id, prefs);
}

/**
 * SetLayout saves the sidebar width and the detail panel's dock and size.
 */
export function SetLayout(layout: appconfig$0.Layout): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(1286510778, layout);
}

/**
 * SetTabOrder saves the order the user dragged their tabs into.
 */
export function SetTabOrder(order: appconfig$0.TabRef[] | null): $CancellablePromise<appconfig$0.Settings> {
    return $Call.ByID(477788357, order);
}
