// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cell is one table cell. Tone lets the frontend colour a value without having
 * to know what the value means: "ok", "warn", "error", "info" or "" for plain.
 */
export interface Cell {
    "text": string;
    "tone": string;

    /**
     * Pills, where a cell is drawn as rectangles rather than written out. Empty
     * for every kind but one, and an empty one renders as Text exactly as
     * before.
     */
    "pills": Pill[] | null;

    /**
     * Sort is compared in place of Text where the two do not share an order.
     * An age reads "3d" but belongs in seconds; a volume reads "500Mi" but
     * belongs in bytes. Sorting the text would put "5m" before "2h" before
     * "3d". Empty means Text is already in the right order.
     */
    "sort": string;
}

/**
 * ContainerRef names one stream: a container, in a pod.
 */
export interface ContainerRef {
    "pod": string;
    "container": string;

    /**
     * Init marks a container that runs to completion before the others start.
     */
    "init": boolean;
}

/**
 * Context is one kubeconfig context flattened with the details the UI needs, so
 * the frontend never has to cross-reference the clusters and users lists.
 */
export interface Context {
    "id": string;
    "name": string;
    "cluster": string;
    "user": string;
    "namespace": string;
    "server": string;
    "file": string;
    "current": boolean;
}

/**
 * CustomResourceGroup is one API group and the kinds defined under it.
 */
export interface CustomResourceGroup {
    "group": string;
    "kinds": CustomResourceKind[] | null;
}

/**
 * CustomResourceKind describes one CRD well enough for the frontend to open a
 * tab on it without asking the backend what it is called.
 */
export interface CustomResourceKind {
    /**
     * the "crd:" string a tab is opened with
     */
    "kind": string;

    /**
     * the CRD's own plural display name
     */
    "label": string;
    "group": string;
    "plural": string;

    /**
     * namespaced rather than cluster-wide
     */
    "scoped": boolean;
}

/**
 * DrainProgress is one report from a drain in flight.
 */
export interface DrainProgress {
    "drainId": string;
    "node": string;

    /**
     * Phase is "cordoning", "planning", "evicting", "done" or "failed".
     */
    "phase": string;
    "evicted": number;
    "total": number;
    "refused": Refusal[] | null;
    "error": string;
    "done": boolean;
}

/**
 * File is a kubeconfig file on disk together with the contexts parsed out of
 * it. A file that failed to parse is still returned, with Error set, so the
 * sidebar can show it as broken rather than silently dropping it.
 */
export interface File {
    "path": string;
    "source": string;
    "contexts": Context[] | null;
    "error": string;
}

/**
 * Gauge is a used/capacity measure on the dashboard.
 */
export interface Gauge {
    "label": string;
    "used": number;
    "capacity": number;
    "unit": string;
}

/**
 * LogBatch is what crosses to the frontend: the lines that gathered since the
 * last one, or the news that a stream has ended.
 */
export interface LogBatch {
    "streamId": string;
    "lines": LogLine[] | null;
    "error": string;
    "done": boolean;
}

/**
 * LogLine is one line, tagged with where it came from -- which is the whole
 * point of a merged view.
 */
export interface LogLine {
    "pod": string;
    "container": string;
    "text": string;
}

/**
 * ObjectState is what the action bar needs to know about an object beyond its
 * name: which of its buttons apply, and what they should start from.
 */
export interface ObjectState {
    /**
     * Scalable reports whether the object carries a replica count. The
     * workloads that have one are exactly the ones worth offering Scale for.
     */
    "scalable": boolean;
    "replicas": number;

    /**
     * Cordoned is a node's spec.unschedulable, which decides whether its button
     * offers to cordon or to uncordon.
     */
    "cordoned": boolean;

    /**
     * Containers is a pod's containers as the same squares the table draws.
     * The panel shows the row again and uses it as the log view's picker, so
     * the call it already makes carries them rather than making a second.
     */
    "containers": Pill[] | null;
}

/**
 * Overview is the dashboard payload for one context.
 */
export interface Overview {
    "contextId": string;
    "context": string;
    "cluster": string;
    "server": string;
    "version": string;
    "distribution": string;
    "namespaces": string[] | null;
    "stats": Stat[] | null;
    "gauges": Gauge[] | null;

    /**
     * Events is the same Table the events tab renders, capped to what the
     * dashboard has room for, so both are sorted and sortable by the same code
     * rather than by two implementations that can disagree.
     */
    "events": Table;
    "error": string;
}

/**
 * Pill is one small rectangle drawn in place of text: a pod's container, with
 * its state carried by colour so a screen of pods can be scanned rather than
 * read. Label and Detail are what a tooltip and a screen reader get.
 */
export interface Pill {
    "label": string;
    "tone": string;
    "detail": string;
}

/**
 * PodRef names one pod. Namespace and name, because that is all an eviction
 * needs and all the panel shows.
 */
export interface PodRef {
    "namespace": string;
    "name": string;
}

/**
 * Refusal is a pod the drain would not move, and why. It is reported rather
 * than acted on: the reasons are the ones kubectl needs a second flag for.
 */
export interface Refusal {
    "pod": PodRef;
    "reason": string;
}

/**
 * Row is one resource in a listing. Name and Namespace are carried separately
 * from Cells because they identify the object for a follow-up Describe call,
 * regardless of which columns the kind happens to render.
 */
export interface Row {
    "id": string;
    "name": string;
    "namespace": string;
    "cells": Cell[] | null;
}

/**
 * Snapshot is one push to the frontend: the whole current contents of a
 * subscribed collection.
 * 
 * Deltas would be cheaper on the wire, but a Row is a *projection* of an object
 * and the frontend cannot apply a delta without redoing that projection. The
 * informer keeps a local cache, so rebuilding the entire table costs no API
 * traffic at all -- only the projection itself, which is why sending the whole
 * thing is affordable.
 */
export interface Snapshot {
    "subscriptionId": string;
    "table": Table;
}

/**
 * Stat is a ready/total counter on the dashboard.
 */
export interface Stat {
    "label": string;
    "ready": number;
    "total": number;
}

/**
 * Table is a generic resource listing. Every kind returns this shape so the UI
 * renders them all through one component.
 */
export interface Table {
    "kind": string;
    "columns": string[] | null;
    "rows": Row[] | null;
    "namespaced": boolean;
    "error": string;
}

/**
 * YAMLCheck is the answer to the only question the editor asks while you type:
 * is this still YAML, and if not, where did it stop being YAML?
 * 
 * Line is 1-based and 0 when the parser named none, so the gutter can mark the
 * offending row without the frontend having to read error prose.
 */
export interface YAMLCheck {
    "valid": boolean;
    "message": string;
    "line": number;
}
