// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cell is one table cell. Tone lets the frontend colour a value without having
 * to know what the value means: "ok", "warn", "error", "info" or "" for plain.
 */
export interface Cell {
    "text": string;
    "tone": string;
}

/**
 * Context is one kubeconfig context flattened with the details the UI needs, so
 * the frontend never has to cross-reference the clusters and users lists.
 */
export interface Context {
    "id": string;
    "name": string;
    "cluster": string;
    "user": string;
    "namespace": string;
    "server": string;
    "file": string;
    "current": boolean;
}

/**
 * Event is a cluster event as shown on the dashboard and in the events table.
 */
export interface Event {
    "type": string;
    "reason": string;
    "object": string;
    "message": string;
    "age": string;
}

/**
 * File is a kubeconfig file on disk together with the contexts parsed out of
 * it. A file that failed to parse is still returned, with Error set, so the
 * sidebar can show it as broken rather than silently dropping it.
 */
export interface File {
    "path": string;
    "source": string;
    "contexts": Context[] | null;
    "error": string;
}

/**
 * Gauge is a used/capacity measure on the dashboard.
 */
export interface Gauge {
    "label": string;
    "used": number;
    "capacity": number;
    "unit": string;
}

/**
 * Overview is the dashboard payload for one context.
 */
export interface Overview {
    "contextId": string;
    "context": string;
    "cluster": string;
    "server": string;
    "version": string;
    "distribution": string;
    "namespaces": string[] | null;
    "stats": Stat[] | null;
    "gauges": Gauge[] | null;
    "events": Event[] | null;
    "error": string;
}

/**
 * Row is one resource in a listing. Name and Namespace are carried separately
 * from Cells because they identify the object for a follow-up Describe call,
 * regardless of which columns the kind happens to render.
 */
export interface Row {
    "id": string;
    "name": string;
    "namespace": string;
    "cells": Cell[] | null;
}

/**
 * Stat is a ready/total counter on the dashboard.
 */
export interface Stat {
    "label": string;
    "ready": number;
    "total": number;
}

/**
 * Table is a generic resource listing. Every kind returns this shape so the UI
 * renders them all through one component.
 */
export interface Table {
    "kind": string;
    "columns": string[] | null;
    "rows": Row[] | null;
    "namespaced": boolean;
    "error": string;
}
