// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cell is one table cell. Tone lets the frontend colour a value without having
 * to know what the value means: "ok", "warn", "error", "info" or "" for plain.
 */
export interface Cell {
    "text": string;
    "tone": string;

    /**
     * Sort is compared in place of Text where the two do not share an order.
     * An age reads "3d" but belongs in seconds; a volume reads "500Mi" but
     * belongs in bytes. Sorting the text would put "5m" before "2h" before
     * "3d". Empty means Text is already in the right order.
     */
    "sort": string;
}

/**
 * Context is one kubeconfig context flattened with the details the UI needs, so
 * the frontend never has to cross-reference the clusters and users lists.
 */
export interface Context {
    "id": string;
    "name": string;
    "cluster": string;
    "user": string;
    "namespace": string;
    "server": string;
    "file": string;
    "current": boolean;
}

/**
 * CustomResourceGroup is one API group and the kinds defined under it.
 */
export interface CustomResourceGroup {
    "group": string;
    "kinds": CustomResourceKind[] | null;
}

/**
 * CustomResourceKind describes one CRD well enough for the frontend to open a
 * tab on it without asking the backend what it is called.
 */
export interface CustomResourceKind {
    /**
     * the "crd:" string a tab is opened with
     */
    "kind": string;

    /**
     * the CRD's own plural display name
     */
    "label": string;
    "group": string;
    "plural": string;

    /**
     * namespaced rather than cluster-wide
     */
    "scoped": boolean;
}

/**
 * File is a kubeconfig file on disk together with the contexts parsed out of
 * it. A file that failed to parse is still returned, with Error set, so the
 * sidebar can show it as broken rather than silently dropping it.
 */
export interface File {
    "path": string;
    "source": string;
    "contexts": Context[] | null;
    "error": string;
}

/**
 * Gauge is a used/capacity measure on the dashboard.
 */
export interface Gauge {
    "label": string;
    "used": number;
    "capacity": number;
    "unit": string;
}

/**
 * Overview is the dashboard payload for one context.
 */
export interface Overview {
    "contextId": string;
    "context": string;
    "cluster": string;
    "server": string;
    "version": string;
    "distribution": string;
    "namespaces": string[] | null;
    "stats": Stat[] | null;
    "gauges": Gauge[] | null;

    /**
     * Events is the same Table the events tab renders, capped to what the
     * dashboard has room for, so both are sorted and sortable by the same code
     * rather than by two implementations that can disagree.
     */
    "events": Table;
    "error": string;
}

/**
 * Row is one resource in a listing. Name and Namespace are carried separately
 * from Cells because they identify the object for a follow-up Describe call,
 * regardless of which columns the kind happens to render.
 */
export interface Row {
    "id": string;
    "name": string;
    "namespace": string;
    "cells": Cell[] | null;
}

/**
 * Snapshot is one push to the frontend: the whole current contents of a
 * subscribed collection.
 * 
 * Deltas would be cheaper on the wire, but a Row is a *projection* of an object
 * and the frontend cannot apply a delta without redoing that projection. The
 * informer keeps a local cache, so rebuilding the entire table costs no API
 * traffic at all -- only the projection itself, which is why sending the whole
 * thing is affordable.
 */
export interface Snapshot {
    "subscriptionId": string;
    "table": Table;
}

/**
 * Stat is a ready/total counter on the dashboard.
 */
export interface Stat {
    "label": string;
    "ready": number;
    "total": number;
}

/**
 * Table is a generic resource listing. Every kind returns this shape so the UI
 * renders them all through one component.
 */
export interface Table {
    "kind": string;
    "columns": string[] | null;
    "rows": Row[] | null;
    "namespaced": boolean;
    "error": string;
}

/**
 * YAMLCheck is the answer to the only question the editor asks while you type:
 * is this still YAML, and if not, where did it stop being YAML?
 * 
 * Line is 1-based and 0 when the parser named none, so the gutter can mark the
 * offending row without the frontend having to read error prose.
 */
export interface YAMLCheck {
    "valid": boolean;
    "message": string;
    "line": number;
}
