// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    ContextPrefs,
    Dock,
    DockTabRef,
    Layout,
    Preferences,
    Settings,
    TabRef
} from "./models.js";
