// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ContextPrefs is what the user decided about one kubeconfig context. Alias
 * overrides the context's name in the UI; Color tints its sidebar entry and
 * every tab opened against it. An empty field means "use the default".
 */
export interface ContextPrefs {
    "alias": string;
    "color": string;
}

/**
 * Layout is the arrangement the user last left the window in.
 */
export interface Layout {
    /**
     * right | bottom | left
     */
    "detailDock": string;

    /**
     * px along the docked edge
     */
    "detailSize": number;

    /**
     * px
     */
    "sidebarWidth": number;
}

/**
 * Settings is the whole persisted file.
 */
export interface Settings {
    "manualFiles": string[] | null;
    "contexts": { [_ in string]?: ContextPrefs } | null;
    "tabOrder": TabRef[] | null;
    "layout": Layout;
}

/**
 * TabRef identifies one open tab: a kubeconfig context and the resource kind
 * shown in it. It is stored as a pair rather than a joined string because
 * context IDs contain a file path, so a composite key could not be split back
 * apart reliably.
 */
export interface TabRef {
    "contextId": string;
    "kind": string;
}
