// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ContextPrefs is what the user decided about one kubeconfig context. Alias
 * overrides the context's name in the UI; Color tints its sidebar entry and
 * every tab opened against it. An empty field means "use the default".
 */
export interface ContextPrefs {
    "alias": string;
    "color": string;

    /**
     * CollapsedGroups overrides Layout.CollapsedGroups for this context alone.
     * Nil means "follow the global setting", which is the usual case -- a
     * cluster only carries its own list once the user folds a group for it
     * specifically, e.g. because this is the one cluster with the Gateway API
     * installed.
     */
    "collapsedGroups": string[] | null;
}

/**
 * Layout is the arrangement the user last left the window in.
 */
export interface Layout {
    /**
     * right | bottom | left
     */
    "detailDock": string;

    /**
     * px along the docked edge
     */
    "detailSize": number;

    /**
     * px
     */
    "sidebarWidth": number;

    /**
     * Zoom is the webview scale, 1 being normal size. Persisted so the window
     * comes back the size the user left it readable at.
     */
    "zoom": number;

    /**
     * CollapsedGroups are the sidebar's resource-tree headings the user has
     * folded away. It is deliberately nullable: nil means they have never
     * chosen, which is what lets the frontend fold the specialist groups once
     * on a fresh install, while an empty list is the real choice "show me
     * everything" and must not be defaulted over. The names are the frontend
     * catalogue's group labels; the store only remembers what it is handed.
     * 
     * No omitempty: it would drop an empty list on write, turning "I expanded
     * everything" back into "never chosen" on the next read.
     */
    "collapsedGroups": string[] | null;
}

/**
 * Settings is the whole persisted file.
 */
export interface Settings {
    "manualFiles": string[] | null;

    /**
     * ManualFolders are directories the user asked us to watch. They are kept
     * as folders rather than expanded into their files at the time they were
     * added, so that a config dropped into one later is picked up by the next
     * sync instead of needing to be added by hand.
     */
    "manualFolders": string[] | null;

    /**
     * ExcludedFiles are kubeconfigs found by discovery that the user has said
     * they do not want. A discovered file cannot simply be forgotten -- the
     * next scan would find it again -- so refusing it has to be recorded.
     */
    "excludedFiles": string[] | null;
    "contexts": { [_ in string]?: ContextPrefs } | null;
    "tabOrder": TabRef[] | null;
    "layout": Layout;
}

/**
 * TabRef identifies one open tab: a kubeconfig context and the resource kind
 * shown in it. It is stored as a pair rather than a joined string because
 * context IDs contain a file path, so a composite key could not be split back
 * apart reliably.
 */
export interface TabRef {
    "contextId": string;
    "kind": string;
}
